### ISSUE TITLE
Issue with Interrupt Handling: GeneratorExit and CancelledError Exceptions in UI and LangSmith

### ISSUE THREAD

**Issue by alex-feel** [JoshuaC215/agent-service-toolkit#198]
I'm encountering issues with two graphs. After adding two graphs (which run correctly in LangGraph Studio) to the project, I see different types of errors when running the agents on the UI.

For the **"Cats Only System"** agent, the following error is raised: 

<details>
  <summary>Error</summary>

```
GeneratorExit()  
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/langgraph/pregel/__init__.py", line 2634, in astream
    yield o
GeneratorExit
```
</details>

For the **"Requirements Assistant"** agent, an unexpected exception is raised with this traceback:

<details>
  <summary>Error</summary>

```
Exception: Unexpected error
Traceback:
File "/usr/local/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
File "/usr/local/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
File "/app/streamlit_app.py", line 370, in <module>
    asyncio.run(main())
File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
File "/app/streamlit_app.py", line 174, in main
    await draw_messages(stream, is_new=True)
File "/app/streamlit_app.py", line 225, in draw_messages
    while msg := await anext(messages_agen, None):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/client/client.py", line 293, in astream
    parsed = self._parse_stream_line(line)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/client/client.py", line 190, in _parse_stream_line
    raise Exception(parsed["content"])
```
</details>

Here what I see in the LangSmith:

<details>
  <summary>Error</summary>

```
CancelledError('Cancelled by cancel scope 7fedb059f590', <Task cancelled name='Task-2953' coro=<AsyncExitStack.__aexit__() done, defined at /usr/local/lib/python3.12/contextlib.py:707>>)Traceback (most recent call last):


  File "/usr/local/lib/python3.12/site-packages/langgraph/pregel/__init__.py", line 2626, in astream
    async for _ in runner.atick(


  File "/usr/local/lib/python3.12/site-packages/langgraph/pregel/runner.py", line 364, in atick
    done, inflight = await asyncio.wait(
                     ^^^^^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 464, in wait
    return await _wait(fs, timeout, return_when, loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 550, in _wait
    await waiter


asyncio.exceptions.CancelledError: Cancelled by cancel scope 7fedb059f590



During handling of the above exception, another exception occurred:



Traceback (most recent call last):


  File "/usr/local/lib/python3.12/site-packages/langgraph/pregel/__init__.py", line 2574, in astream
    async with AsyncPregelLoop(


  File "/usr/local/lib/python3.12/site-packages/langgraph/pregel/loop.py", line 1188, in __aexit__
    return await exit_task
           ^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.12/contextlib.py", line 707, in __aexit__
    async def __aexit__(self, *exc_details):


asyncio.exceptions.CancelledError: ('Cancelled by cancel scope 7fedb059f590', <Task cancelled name='Task-2953' coro=<AsyncExitStack.__aexit__() done, defined at /usr/local/lib/python3.12/contextlib.py:707>>)
```
</details>

Although the **"Requirements Assistant"** agent sends the expected interrupt output (for example, an interrupt message like:  

```
GraphInterrupt((Interrupt(value='The requirements are ready. If you have any comments, remarks or additional requirements, send them to me and I will continue working.', resumable=True, ns=[...]),))
```

these errors still appear in the UI and LangSmith logs.

**Steps to Reproduce:**  
1. Use the [project](https://github.com/alex-feel/agent-service-toolkit).  
2. Run the agents “Cats Only System” and “Requirements Assistant”.  
3. Observe the error outputs described above.

**Expected Behavior:**  
In LangGraph Studio, both graphs run as expected with the interrupt mechanism properly pausing execution and resuming once input is provided. The same behavior is expected for the UI.

It appears that when the interrupt is triggered, asynchronous cancellation (reflected by `GeneratorExit` and `CancelledError`) is not handled in the UI and LangSmith contexts. This might indicate an integration or exception-handling issue with how these environments resume the graph after an interrupt.

Thank you for your help and for your work on this project!

**Comment by txc-link** [comment]
Have you solved it? I have the same problem.

**Comment by txc-link** [comment]
> Have you solved it? I have the same problem.

![Image](https://github.com/user-attachments/assets/40527315-f627-4c36-a695-d64fda9bf0f9)Turn off the Stream results will be fine

**Comment by txc-link** [comment]
> Have you solved it? I have the same problem.

![Image](https://github.com/user-attachments/assets/f6b4dfa4-9df4-4136-9fba-6c9f3968128f)
Turn off the Stream results will be fine.

**Comment by txc-link** [comment]
> Have you solved it? I have the same problem.

![Image](https://github.com/user-attachments/assets/4d4d3462-07fd-4278-9f42-c1514e8b4723)

Turn Off the Stream results will be fine.

**Comment by alex-feel** [comment]
> Have you solved it? I have the same problem.

No, I haven't solved it yet. Additionally, when I disable the "Stream results" feature, I am unable to view any **AI** messages in the UI.

**Comment by JoshuaC215** [comment]
Hi folks,
Since you're referencing agents that aren't checked into the project, I'm not able to directly reproduce this issue. I just merged in https://github.com/JoshuaC215/agent-service-toolkit/pull/203 which might help. Let me know if that happens to resolve it (I'm not sure if it will).

If someone can provide a reference to example agent code and specific input that produces this error / behavior, I can take a closer look. It may have to do with the returned/expected format for interrupt messages.

**Comment by alex-feel** [comment]
@JoshuaC215,

Thank you for your prompt response and for merging PR #203. Unfortunately, the issue persists, and the behavior remains unchanged.

As mentioned in my initial message, I've provided a reference repository with the two agents added: [https://github.com/alex-feel/agent-service-toolkit](https://github.com/alex-feel/agent-service-toolkit). This repository is ready for testing; you can clone it and add the necessary API keys to the environment variables. The **"Cats Only System"** agent can be used almost immediately.

Regarding the **"Requirements Assistant"** agent, I'm prepared to provide any additional information, including videos and traces, if that would be helpful. However, reviewing its source code might already offer some insights.

As previously noted, disabling streaming doesn't resolve the issue. After disabling, the UI displays only the interrupt messages, but AI messages are not shown at all, even though they are correctly added to the `messages` field in the state. Interestingly, these same agents work correctly with the UI from the following repository: [https://github.com/langchain-ai/agent-chat-ui](https://github.com/langchain-ai/agent-chat-ui), but the UI has other issues with interrupts.

Thank you!

**Comment by JoshuaC215** [comment]
Ahh so sorry, I missed the original link to your fork. Yes, I'll take a closer look when I have some time - it may take me a week or so.

**Comment by alex-feel** [comment]
@JoshuaC215, thank you for the fix and your thoughts!

I traced the issue to partial tuple fragments in the streamed messages — content and tool_calls were arriving as separate tuples and not being reassembled. I’ve opened a PR that adds logic to reconstruct those tuples into a proper `AIMessage` (skipping metadata tuples): https://github.com/JoshuaC215/agent-service-toolkit/pull/216.

Thanks for your work!

**Comment by alex-feel** [comment]
I believe the issue is resolved. Thank you!
